#!/bin/bash

echo "🗄️  Database Setup for InterviewMatrix"
echo "======================================="
echo ""
echo "📋 Quick Steps:"
echo ""
echo "1. Get Free PostgreSQL Database (2 min):"
echo "   → Visit: https://neon.tech"
echo "   → Sign up with GitHub (fastest)"
echo "   → Create new project"
echo "   → Copy connection string"
echo ""
echo "2. Your connection string will look like:"
echo "   postgresql://user:password@ep-xxx.us-east-2.aws.neon.tech/neondb"
echo ""
echo "3. Update .env file:"
echo '   DATABASE_URL="your-connection-string-here"'
echo ""
echo "4. Create database tables:"
echo "   npx prisma db push"
echo ""
echo "5. Restart dev server:"
echo "   npm run dev"
echo ""
echo "✨ Alternative providers (also free):"
echo "   • Supabase: https://supabase.com"
echo "   • Railway: https://railway.app"
echo "   • Vercel Postgres: https://vercel.com/storage/postgres"
echo ""
echo "📖 See STATUS.md for detailed instructions"
